import { createFileRoute } from "@tanstack/react-router";
import { BellRing, CheckCircle2, LayoutGrid, Palette, Volume2 } from "lucide-react";
import { useState } from "react";
import { AppLayout } from "@/layouts/AppLayout";
import { Switch } from "@/components/ui/switch";

export const Route = createFileRoute("/configuracoes")({ head: () => ({ meta: [{ title: "Configurações | Puket Cadastro Inteligente" }, { name: "description", content: "Preferências visuais demonstrativas do sistema." }] }), component: Configuracoes });
const settings = [{ id: "confirm", title: "Confirmar antes de executar", description: "Exibe uma confirmação antes de iniciar uma automação.", icon: CheckCircle2 }, { id: "sound", title: "Som de conclusão", description: "Toca um aviso suave quando uma operação terminar.", icon: Volume2 }, { id: "notifications", title: "Notificações", description: "Mostra novidades e pendências no cabeçalho.", icon: BellRing }, { id: "compact", title: "Modo compacto", description: "Reduz o espaçamento das listas e dos resultados.", icon: LayoutGrid }];
function Configuracoes() { const [enabled, setEnabled] = useState<Record<string, boolean>>({ confirm: true, sound: true, notifications: true, compact: false }); return <AppLayout><div className="mb-7"><p className="text-sm font-extrabold uppercase tracking-[.18em] text-primary">Preferências</p><h1 className="mt-2 font-display text-3xl font-extrabold sm:text-4xl">Deixe do seu jeito</h1><p className="mt-2 text-muted-foreground">Configurações apenas visuais durante o modo demonstração.</p></div><div className="grid gap-5 lg:grid-cols-[1fr_.7fr]"><section className="surface-card divide-y overflow-hidden">{settings.map(({ id, title, description, icon: Icon }) => <div key={id} className="flex items-center gap-4 p-5"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-primary-soft text-primary"><Icon className="h-5 w-5" /></span><div className="min-w-0 flex-1"><h2 className="font-bold">{title}</h2><p className="text-sm text-muted-foreground">{description}</p></div><Switch checked={Boolean(enabled[id])} onCheckedChange={(value) => setEnabled((current) => ({ ...current, [id]: value }))} aria-label={title} /></div>)}</section><aside className="surface-card h-fit p-6"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-accent-soft text-accent-foreground"><Palette className="h-6 w-6" /></span><h2 className="mt-4 font-display text-xl font-bold">Aparência Puket</h2><p className="mt-2 text-sm text-muted-foreground">A paleta alegre, os cantos arredondados e a tipografia acolhedora já estão aplicados em todo o sistema.</p><div className="mt-5 flex gap-2">{["bg-primary", "bg-accent", "bg-info", "bg-grape"].map((color) => <span key={color} className={`h-10 flex-1 rounded-xl ${color}`} />)}</div></aside></div></AppLayout>; }
