import { useState } from "react";
import type { ReactNode } from "react";
import { AlertTriangle, ArrowLeft, Check, PackagePlus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import type { KitPreviewData, ProductEdits } from "@/types";

const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const Field = ({ label, children }: { label: string; children: ReactNode }) => <div><Label>{label}</Label>{children}</div>;

export function KitPreview({ preview, onBack, onApprove }: { preview: KitPreviewData; onBack: () => void; onApprove: (edits: ProductEdits) => void }) {
  const kit = preview.kit;
  const [edits, setEdits] = useState<ProductEdits>({ name: kit.name, description: kit.description, price: kit.price, images: kit.images, ncm: kit.ncm, categoryId: kit.categoryId, dimensions: { width: kit.dimensions.width, height: kit.dimensions.height, depth: kit.dimensions.depth }, netWeight: kit.dimensions.netWeight, grossWeight: kit.dimensions.grossWeight });
  const toggleImage = (url: string) => setEdits(value => ({ ...value, images: value.images.includes(url) ? value.images.filter(item => item !== url) : [...value.images, url] }));
  const makePrimary = (url: string) => setEdits(value => ({ ...value, images: [url, ...value.images.filter(item => item !== url)] }));
  const valid = Boolean(edits.name.trim() && edits.price >= 0 && /^[0-9.]{8,10}$/.test(edits.ncm) && edits.categoryId > 0);
  return <section className="surface-card mx-auto w-full max-w-4xl overflow-hidden">
    <div className="border-b border-border bg-gradient-to-r from-primary-soft via-background to-accent/15 p-5 sm:p-7"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-primary">Criar kit · confira antes de enviar</p><h2 className="mt-2 font-display text-2xl font-extrabold sm:text-3xl">{edits.name}</h2><div className="mt-4 flex flex-wrap gap-2 text-sm"><span className="rounded-full bg-background px-3 py-1 font-bold">{preview.components.length} componentes</span><span className="rounded-full bg-background px-3 py-1 font-bold">{money.format(edits.price)}</span><span className="rounded-full bg-background px-3 py-1 font-bold">Estoque possível: {kit.availability}</span>{kit.exists && <span className="rounded-full bg-success-soft px-3 py-1 font-bold text-success-foreground">Estrutura existente</span>}{kit.productExists && kit.structureStatus === "missing" && <span className="rounded-full bg-info-soft px-3 py-1 font-bold text-info-foreground">Será convertido em kit</span>}</div></div>
    <div className="space-y-6 p-5 sm:p-7">
      <div className="rounded-3xl border border-border bg-secondary/25 p-4 sm:p-5"><h3 className="font-display text-lg font-bold">Dados do kit</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Nome"><Input className="mt-1.5 rounded-xl" value={edits.name} onChange={e => setEdits(v => ({ ...v, name: e.target.value }))}/></Field><Field label="Preço final"><Input type="number" min="0" step="0.01" className="mt-1.5 rounded-xl" value={edits.price} onChange={e => setEdits(v => ({ ...v, price: Number(e.target.value) }))}/></Field><Field label="NCM"><Input className="mt-1.5 rounded-xl" value={edits.ncm} onChange={e => setEdits(v => ({ ...v, ncm: e.target.value }))}/></Field><Field label="ID da categoria"><Input type="number" min="1" className="mt-1.5 rounded-xl" value={edits.categoryId} onChange={e => setEdits(v => ({ ...v, categoryId: Number(e.target.value) }))}/></Field><div className="sm:col-span-2"><Label>Descrição</Label><Textarea rows={6} className="mt-1.5 rounded-xl" value={edits.description} onChange={e => setEdits(v => ({ ...v, description: e.target.value }))}/></div></div></div>
      <div className="rounded-3xl border border-border p-4 sm:p-5"><h3 className="font-display text-lg font-bold">Imagens do kit</h3>{kit.images.length ? <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{kit.images.map(url => { const selected = edits.images.includes(url); return <div key={url} className={`overflow-hidden rounded-2xl border-2 ${selected ? "border-primary" : "border-border"}`}><button type="button" className="aspect-square w-full bg-white" onClick={() => toggleImage(url)}><img src={url} alt="Produto do kit" className="h-full w-full object-contain p-2"/></button><Button type="button" size="sm" variant={edits.images[0] === url ? "default" : "outline"} disabled={!selected} className="m-2 w-[calc(100%-1rem)] rounded-full text-xs" onClick={() => makePrimary(url)}>{edits.images[0] === url ? "Principal" : "Tornar principal"}</Button></div>; })}</div> : <p className="mt-3 text-sm text-muted-foreground">Nenhuma imagem encontrada.</p>}</div>
      <div className="rounded-3xl border border-border bg-secondary/25 p-4 sm:p-5"><h3 className="font-display text-lg font-bold">Medidas e peso</h3><div className="mt-4 grid gap-4 sm:grid-cols-3">{([['width','Largura (cm)'],['height','Altura (cm)'],['depth','Comprimento (cm)']] as const).map(([key,label]) => <Field key={key} label={label}><Input type="number" min="0" step="0.01" className="mt-1.5 rounded-xl" value={edits.dimensions[key]} onChange={e => setEdits(v => ({ ...v, dimensions: { ...v.dimensions, [key]: Number(e.target.value) } }))}/></Field>)}<Field label="Peso líquido (kg)"><Input type="number" min="0" step="0.001" className="mt-1.5 rounded-xl" value={edits.netWeight} onChange={e => setEdits(v => ({ ...v, netWeight: Number(e.target.value) }))}/></Field><Field label="Peso bruto (kg)"><Input type="number" min="0" step="0.001" className="mt-1.5 rounded-xl" value={edits.grossWeight} onChange={e => setEdits(v => ({ ...v, grossWeight: Number(e.target.value) }))}/></Field></div></div>
      <div><h3 className="font-display text-lg font-bold">Componentes</h3><div className="mt-3 space-y-3">{preview.components.map(item => <article key={item.requestedSku} className="flex gap-4 rounded-2xl border border-border p-4"><div className="grid h-20 w-20 shrink-0 place-items-center overflow-hidden rounded-2xl bg-white">{item.image ? <img src={item.image} alt={item.name} className="h-full w-full object-contain p-1"/> : <PackagePlus className="h-8 w-8 text-muted-foreground"/>}</div><div className="min-w-0 flex-1"><p className="font-bold">{item.name}</p><p className="font-mono text-xs text-muted-foreground">{item.childSku} · {item.barcode}</p><p className="mt-2 text-sm font-semibold">{money.format(item.price)} · Estoque: {item.stock}</p></div><span className={`h-fit rounded-full px-3 py-1 text-xs font-bold ${item.status === "existing" ? "bg-success-soft text-success-foreground" : item.status === "missing" ? "bg-info-soft text-info-foreground" : "bg-destructive-soft text-destructive"}`}>{item.status === "existing" ? "Já existe" : item.status === "missing" ? "Será criado" : "Duplicidade"}</span></article>)}</div></div>
      {preview.warnings.length > 0 && <div className="rounded-2xl bg-destructive-soft p-4 text-sm text-destructive"><p className="flex items-center gap-2 font-bold"><AlertTriangle className="h-4 w-4"/>Revise antes de continuar</p>{preview.warnings.map(item => <p key={item}>• {item}</p>)}</div>}
      <div className="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><Button variant="outline" className="h-12 rounded-full px-6" onClick={onBack}><ArrowLeft className="h-4 w-4"/>Voltar</Button><Button className="h-12 rounded-full px-8 font-bold" disabled={!preview.canApprove || !valid} onClick={() => onApprove(edits)}><Check className="h-5 w-5"/>{kit.exists ? "Salvar alterações do kit" : "Confirmar e criar kit"}</Button></div>
    </div>
  </section>;
}
